language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
mono:
  - 4.2.2
os:
  - linux
  - osx
osx_image: xcode7.1
matrix:
  allow_failures:
    - os: osx
script:
  - ./build.sh verify
notifications:
  email:
    on_failure: change
